### ISSUE TITLE
"Source Control" and "Run and Debug" Icons differ significantly from the original Codicons

### ISSUE THREAD

**Issue by 1nVitr0** [material-extensions/vscode-material-product-icons#11]
I'm aware that this might be intended, but both the "Source Control" as well as the "Run and Debug" icons differ so much from the original, that I think it might be confusing for users. Especially the new "Source Control" icon is extremely similar to GitLens "File History" which I actually use in it's own Action Bar tab.

- "Source Control": Original ![source-control](https://raw.githubusercontent.com/microsoft/vscode-codicons/main/src/icons/source-control.svg), New <img src="https://raw.githubusercontent.com/PKief/vscode-material-product-icons/master/icons/uEA03-source-control.svg" width="32px" height="32px">
- "Run and Debug": Original ![debug-alt](https://raw.githubusercontent.com/microsoft/vscode-codicons/main/src/icons/debug-alt.svg), New <img src="https://raw.githubusercontent.com/PKief/vscode-material-product-icons/master/icons/uEA04-rocket.svg" width="32px" height="32px">

I believe that changing these icons to be more in line with the original icons will ease the transition to the (admittedly better looking) material icons, especially for longtime users of vscode.

**Comment by 1nVitr0** [comment]
I believe just switching to the extisting icons `debug-alt` <img src="https://raw.githubusercontent.com/PKief/vscode-material-product-icons/master/icons/uEB2D-debug-alt.svg" witdh="32px" height="32px"> and `source-branch` <img src="https://raw.githubusercontent.com/PKief/vscode-material-product-icons/master/icons/uEA1B-source-branch.svg" witdh="32px" height="32px"> might do the job

**Comment by Guema** [comment]
Same opinion here, really efficient and accurate ticket

**Comment by PKief** [comment]
I agree with you, it might be confusing. So I changed it as suggested by you.
