### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by whippingdot** [material-extensions/vscode-material-product-icons#12]
Hey, can you add some product icons for the gitlens and project manager extensions? These are pretty popular, and they are not as soft as your product icons so they don't fit well. Thanks for the awesome product, again! These icons are as great as the file icons u made that I use

**Comment by PKief** [comment]
Unfortunately, I can't edit these symbols because they are brought by the extensions themselves. Please contact the authors of the extensions and ask if they want to use the customizable icons from VS Code, then I have a way to replace them with my own.
