### ISSUE TITLE
Publish to open-vsx.org

### ISSUE THREAD

**Issue by benmontour** [material-extensions/vscode-material-product-icons#13]
Have you considered publishing your extensions to open-vsx.org? Users of VSCodium and other open source VSCode based editors would love to be able to use your themes and icon packs.
https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

**Comment by PKief** [comment]
Hi I didn't considered it yet. What would be the advantage of this? Haven't used open-vsx.org before. Would I need to republish it again every time, when I publish a new version on the official Marketplace? What makes it different to the Marketplace of Microsoft, especially for my extension?

**Comment by benmontour** [comment]
The difference between open-vsx and the official Microsoft marketplace is that it is legally questionable if open source VS Code based editors are allowed to use the official Microsoft marketplace.
Publishing to open-vsx allows those who run the [open source versions of VS Code](https://github.com/microsoft/vscode) such as [VSCodium](https://github.com/VSCodium/vscodium) to have access to the same extensions as the non-OSS VS Code.
I'm not an extension developer, only a consumer, so I'm unsure of the process for publishing. I do know that the community has created a [GitHub Action that can publish to open-vsx.org automatically](https://github.com/HaaLeo/publish-vscode-extension#readme). 
It's ok either way, I just enjoy your product icons and thought it would be nice to have them in VSCodium.

**Comment by PKief** [comment]
Thank you for your feedback. I will try to publish the extension for VSCodium as well 👍

**Comment by PKief** [comment]
@benmontour It has been published!

https://open-vsx.org/extension/PKief/material-product-icons

**Comment by benmontour** [comment]
Thank you!
