### ISSUE TITLE
Preview Icon

### ISSUE THREAD

**Issue by junaga** [material-extensions/vscode-material-product-icons#17]
In my opinion this "Markdown Preview" looks kinda strange..
![image](https://user-images.githubusercontent.com/35770913/120032904-2bf36500-bffb-11eb-9a8a-567e47e0a25b.png)

How about this `preview` [Icon](https://fonts.google.com/icons?selected=Material+Icons&icon.query=Preview). I honestly think it would make a really good fit.

**Comment by PKief** [comment]
What do you think about the eye symbol?

![image](https://user-images.githubusercontent.com/12248527/121593281-05421f00-ca3c-11eb-9d83-8b36f123ce83.png)

Would be fine for me to change that. Looking forward to your feedback :)

**Comment by junaga** [comment]
I am not so sure, I'm a bad designer. But I think I would prefer this Icon.
![baseline_preview_black_24dp](https://user-images.githubusercontent.com/35770913/121735822-f79d9f80-caf6-11eb-84d5-68aac2a04e00.png) [source](https://fonts.google.com/icons?selected=Material+Icons&icon.query=Preview)

The preview button is more than a state change in UI. It does rendering, everyone knows that. That's probably why Google put the Box around the eye, because a "preview" includes a process. I honestly think it would be more intuitive with the box.

**Comment by junaga** [comment]
What do you think?

**Comment by junaga** [comment]
@PKief

**Comment by PKief** [comment]
I think it looks good, I added the icon as suggested. Will be part of the next update.
