### ISSUE TITLE
Not working on GitHub codespace

### ISSUE THREAD

**Issue by shivapoudel** [material-extensions/vscode-material-product-icons#20]
Now you can open any repository in codespace using `.` key shortcut. See https://twitter.com/github/status/1425505817827151872?s=20

When my setting is synced by signing in this extension is activated but still, all icons are missing. Any opportunity to get this extension working in codespace?

**Comment by PKief** [comment]
Thank you for informing me about this. Right now I'm not sure why it's not working properly. In the browser console I get an error like this:

> Refused to load the font 'https://pkief.vscode-unpkg.net/PKief/material-product-icons/1.0.4/extension/theme/material-icons.woff' because it violates the following Content Security Policy directive: "font-src 'self'

**Comment by shivapoudel** [comment]
@PKief Also keep an eye on your other project for the file icons. It is also not being able to install in VSCode web :)

**Comment by PKief** [comment]
I already checked that, but got the [information](https://github.com/microsoft/vscode-remote-release/issues/2343#issuecomment-591328438) from @aeschli that it will work for the web version if I have set the `extensionKind` to 

```json
"extensionKind": ["ui", "workspace"]
```

Not sure why it's not availabe to be used in code spaces.

**Comment by aeschli** [comment]
@PKief For an extension with code to run in the browser only environment it needs a new entry point `browser`. In the one will be used instead of `main`. All code needs to be packaged to a single file and the only `require` possible is for `vscode`.
We are working on the documentation for this.

**Comment by shivapoudel** [comment]
@PKief A little update, this extension works well in Codespaces which I had tried it just now. But unfortunately VSCode icons the next project is missing to work on Codespaces.

For the Browser VSCode installation which is open by pressing `.` key, I was unable to install VSCode icons but Product icons seems installed but won't work.

**Comment by PKief** [comment]
Seems to work now:

![image](https://user-images.githubusercontent.com/12248527/152659165-0a6bc38d-addf-44d9-8caa-f07f7a65977f.png)
