### ISSUE TITLE
Unintuitive icons for jupter cell toolbar

### ISSUE THREAD

**Issue by Igorgro** [material-extensions/vscode-material-product-icons#27]
Here are icons from the default product theme:
![изображение](https://user-images.githubusercontent.com/22894169/130277883-6a47da34-221c-4db3-9148-60d2f15adeeb.png)
the first two of them means "run cells above" and "run cells below", which is quite obvious.

This is the same toolbar, but with material icon theme:
![изображение](https://user-images.githubusercontent.com/22894169/130278048-08cb42db-1e55-4f06-b08b-d799b67b92a1.png)
this icons are not so obvious and can be interpreted as "move cell up" and "move cell down". Can they be replaced with more clear ones?

**Comment by Igorgro** [comment]
@PKief is this repository abandoned?

**Comment by PKief** [comment]
No, I'm still the maintainer of it. But I'm not only an open source maintainer but also professional software engineer at my company. This is why it's quite heavy to respond to all issues in multiple repositories and projects. I usually quickly decide if things are important like answering to this question or if I can fix and finally resolve an issue. But sometimes issues stay open until other developers provide good pull requests or until I find some time to care about it. I hope you can understand this :) 

If you could give me a favor you could enable the developer tools in VS Code and check the HTML code of these icons and what names the icons have. Then I can check if it's possible to replace these icons. Currently I'm not working with jupyter at all, so this would help a lot.

**Comment by Igorgro** [comment]
Thank you for fixing that. Unfortunately the icons haven't changed. This is how the toolbar looks like in the latest version of vscode with this extension enabled: 
![image](https://user-images.githubusercontent.com/22894169/153730284-9cea20ca-4d0e-4730-9045-f435bb6deac3.png)

**Comment by PKief** [comment]
Thanks for reporting this, will check it 👍

**Comment by PKief** [comment]
@Igorgro Should be fixed with the last update:

![image](https://user-images.githubusercontent.com/12248527/159140719-f8392fe1-214f-4d4a-9983-efe7258b2735.png)

**Comment by PKief** [comment]
@Igorgro please let me know if there's still something missing ;)
