### ISSUE TITLE
Restart and Disconnect debuggin use the same icon

### ISSUE THREAD

**Issue by hauseyo** [material-extensions/vscode-material-product-icons#28]
Hi, 
I see that the 'Restart' and 'Disconnect' buttons are using the same icon.
Could you please add an icon for 'Disconnect' button?

<img width="167" alt="Screenshot 2021-10-23 at 01 24 37" src="https://user-images.githubusercontent.com/63884278/138529505-92e4b2a8-f4c3-4557-86ae-2bd63fe56ff2.png">

Thank you and best regards.

Extension version: 1.1.1
VS Code version: 1.61.2

**Comment by PKief** [comment]
Thank you! I fixed it and it will be part of the next update on the Marketplace. Please excuse the late reaction.
