### ISSUE TITLE
Change disconnect/stop icon from reset

### ISSUE THREAD

**Issue by RadhiRasho** [material-extensions/vscode-material-product-icons#29]
This Icon doesn't make sense especially when the reset is sitting right next to it: 

![image](https://user-images.githubusercontent.com/54078496/151624188-705b894f-c76d-4e4c-b7c8-4b0255d3a41d.png)

probably also switch the sync vs refresh icons on source control tab: 

![image](https://user-images.githubusercontent.com/54078496/151624351-6228c0f1-dfa2-484a-89e1-ad56f301e31a.png)

**Comment by PKief** [comment]
Sorry I think it was already [fixed](https://github.com/PKief/vscode-material-product-icons/commit/9dea79cc8e78cbb0bdbef56881778027383a8160) but not published yet. I will update it on the Marketplace very soon. Thanks for the notification :)

**Comment by RadhiRasho** [comment]
No worries, glad to be of any help!
