### ISSUE TITLE
Strange icons in the "View" menu

### ISSUE THREAD

**Issue by konstantinovaleksej** [material-extensions/vscode-material-product-icons#31]
Hi!
In the last version, I see strange icons. They are located in the "View" menu.

![StrangeIcons](https://user-images.githubusercontent.com/43069025/152672733-13179da0-a77e-4f72-a9ba-9ca8df2fe934.png)

Thank you for your wonderful work!

Extension version: 1.1.2
VS Code version: 1.64.0

**Comment by PKief** [comment]
Thanks for reporting, VS Code has updated something in the last version I was not aware of. I will fix it and publish a new version to the marketplace. Glad to hear that you like this extension :)
