### ISSUE TITLE
Icon in Debug View is Missing

### ISSUE THREAD

**Issue by yttriumz** [material-extensions/vscode-material-product-icons#46]
The little icon before the line number, which indicates the running statement, is missing.

The below screenshot is taken when using VSCode's default product icon. 

![image](https://user-images.githubusercontent.com/43232804/192585209-abfe9029-42d7-4284-87f3-28a1a086ca0f.png)

The below screenshot is taken when using our product icon. 

![image](https://user-images.githubusercontent.com/43232804/192585299-c14c3859-c2eb-4e59-ba18-cd732c6e1264.png)

**Comment by PKief** [comment]
Thank you very much for creating this issue! I've been debugging for so many times and didn't notice that this icon was missing. Will be fixed very soon :)
