### ISSUE TITLE
Live Share Icon?

### ISSUE THREAD

**Issue by NathanHannon** [material-extensions/vscode-material-product-icons#7]
I'm not sure where to leave icon suggestions. But I was wondering if it would be possible to make an icon for the [Live Share](https://marketplace.visualstudio.com/items?itemName=MS-vsliveshare.vsliveshare) extension

**Comment by PKief** [comment]
Some extensions are using their own icons which cannot be replaced by this extension.

**Comment by PKief** [comment]
So to make it possible you'd have to ask the extension owner (in this case Microsoft) if they could use one of the icons which are provided by VS Code. These icons can be replaced. So if you mind, you could open an issue in the live share repository and you could ask them to change this :)

**Comment by NathanHannon** [comment]
Yeah, I wasn't aware of that until after opening an issue :)
