### ISSUE TITLE
[Issue] Installing on Code-Server

### ISSUE THREAD

**Issue by MiguelNdeCarvalho** [material-extensions/vscode-material-product-icons#8]
Hey,

I really enjoy this icons and I tried to install it in my `code-server` but I couldn't find it in the store, then I tried to install the `.vsix` manually and it said that the wasn't compatible with the vscode version.

**Code-Server version:**
```
code-server: v3.9.0
 VS Code: v1.52.1
Commit: fc6d123da59a4e5a675ac8e080f66e032ba01a1b
Date: 2021-02-12T23:39:50Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.192 Safari/537.36
```

Thanks,
MiguelNdeCarvalho

**Comment by PKief** [comment]
Hi, this type of extension was introduced first with VS Code 1.53. So you should update your VS Code version to at least 1.53

**Comment by MiguelNdeCarvalho** [comment]
Hey,
I have asked this because `code-server` last version is using `1.52.1`, isn't possible for you to give support for 1.52.x?
Thanks,
MiguelNdeCarvalho

**Comment by PKief** [comment]
Unfortunately, this feature was first introduced with VS Code 1.53. So there's no VS Code version before that does support this extension API. Therefore it is not possible for me to change the supported version of this extension. Interesting that there's no version 1.53 for the code-server. I would have expected that VS Code Team would sync their changes also into the vscode-server and update it at the same time as the normal VS Code.

**Comment by MiguelNdeCarvalho** [comment]
Hey,

That's really said to see that I can't use it yet. I saw a [PR](https://github.com/cdr/code-server/pull/2773) that updates their base to 1.53. They should merge that this week or sooner.

Thanks for everything,
MiguelNdeCarvalho
